version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5002:5002"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=5002
    volumes:
      - ./backend:/app/backend
      - chatbot_data:/app/data
    command: python backend/app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: .
    ports:
      - "8501:8501"
    environment:
      - BACKEND_API_URL=http://backend:5002/api
      - PORT=8501
    volumes:
      - ./frontend:/app/frontend
    command: streamlit run frontend/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - backend

volumes:
  chatbot_data: 